
version: 2

models:
  - name: Tran1
    description: "A starter dbt model"
    columns:
      - name: Tranid
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
